name: Build and Package MSI

on:
  push:
    branches:
      - desenvolvimento
  pull_request:
    branches:
      - desenvolvimento

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Package MSI
        run: ./gradlew packageMsi

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: StudentManagementApp
          path: composeApp/build/compose/binaries/main/msi/*.msi
